### ISSUE TITLE
err: malformed utf-8 data

### ISSUE THREAD

**Issue by MegaBytee** [hiveauth/hive-auth-wrapper#1]
the authenticate(..) work perfectly so when i store the authdata and try to broadcast a transaction i get this error on hivekeychain mobile app (hiveauth supported)
  "err: malformed utf-8 data"

code :
they are issue on broadcast() function 
```
const auth = {
                username: hiveAuthData.account,  // (required)
                token: hiveAuthData.token,
                expire: hiveAuthData.expire,
                key: hiveAuthData.uuid
            }
   const op = [
                "vote",
                {
                    voter: auth.username,
                    author: "megabytee",
                    permlink: "hivemash-is-coming-soon-let-s-chat-test-ignore",
                    weight: 10000,
                }
            ]

            console.log(op)
            HAS.broadcast(auth, "posting", [op], (evt: any) => {
                console.log(evt)
            })
                .then(res => approve(res))  // Authentication request approved
                .catch(err => reject(err))  // Authentication request rejected or error occured

```
can you help me fix the issue , i don't understand what happening here !!!

**Comment by VIM-Arcange** [comment]
The error message is displayed on Hive Keychain. Therefore, you should contact their support team first.
You may validate it as a Keychain issue by performing the same operation using the HiveAuth mobile app.

**Comment by MegaBytee** [comment]
Ok thanks i fixed the issue :) i get inspired by this code https://github.com/quochuy/hive-auth-client 
it seems that i was doing wrong data formatting in my code no issue on hiveauth or hivekeychain ! it was me :)
